name: findgame
version: '1.0'
main: com.axon.findgame.FindGame
api-version: '1.21'
authors: [ Loft ]
commands:
  findgame:
    description: "Управление мини-игрой FindGame"
    aliases: [fg, find]
    usage: "/<command> [start|stop|reload|help]"

permissions:
  findgame.play:
    description: "Играть в мини-игру"
    default: true
  findgame.admin:
    description: "Админ-команды"
    default: op
